application: firstteam4819
version: 1-1-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
   
- url: /media/.*
  script: serveMedia.app
    
- url: /upload.py
  script: addImage.app

- url: /addImage.py
  script: addImage.app
    
- url: /getPosts.py
  script: getPosts.app
  
- url: /getMiniPosts.py
  script: getPosts.app

- url: /addPost.*
  script: addpost.app
  
- url: /MainPage
  script: addpost.app
  
- url: /Content/(.*)
  mime_type: text/html
  static_files: static/Content/\1.html
  upload: static/Content/(.*)\.html
  
- url: /Content/getSidebar.py
  script: getSidebar.app

- url: /(News|Album|Code|Awards|Sponsors|About|Robots)
  static_files: static/index.html
  upload: static/index.html

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)
  
- url: /(.*\.pdf)
  mime_type: application/pdf
  static_files: static/\1
  upload: static/(.*\.pdf)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# index files
#- url: /(.+)/
#  static_files: static/\1/index.html
#  upload: static/(.+)/index.html

# redirect to 'url + /index.html' url.
#- url: /(.+)
#  static_files: static/redirector.html
#  upload: static/redirector.html

# site root
- url: /
  static_files: static/index.html
  upload: static/index.html

libraries:
- name: webapp2
  version: "2.5.2"
