application: firstteam4819
version: 2-1-0
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:


    
  
- url: /favicon.ico
  static_files: static/Images/Logo/favicon.ico
  upload: static/Images/Logo/favicon.ico
  
- url: /static/media/(.*)
  script: python.media.app
  
- url: /python/newFolder
  script: python.scripts.newFolder.app
  

  
- url: /python/login
  script: python.scripts.login.app
  
- url: /python/logout
  script: python.scripts.logout.app
  
- url: /python/CreateUser
  script: python.scripts.CreateUser.app
  
- url: /python/newPost
  script: python.scripts.newPost.app

- url: /python/editPost
  script: python.scripts.editPost.app
  
- url: /python/newComment
  script: python.scripts.newComment.app
  
- url: /python/subscribe
  script: python.scripts.subscribe.app

- url: /python/unsubscribe
  script: python.scripts.subscribe.app
  
- url: /python/deletePost
  script: python.scripts.editPost.app
  
  
- url: /static/(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /static/(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /static/(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /static/(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)
  
- url: /static/(.*\.pdf)
  mime_type: application/pdf
  static_files: static/\1
  upload: static/(.*\.pdf)

- url: /static/(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)
  
- url: /_ah/mail/.+
  script: python.email.app
  
- url: /_ah/mail/teamBroadcast@firstteam4819.appspotmail.com
  script: python.email.app
  
# image files
- url: /static/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  
- url: /Pages/(.*)
  script: python.getPage.app
  
- url: /upload/(.*)
  script: python.media.app
  
  
- url: /(.*)
  script: python.main.app

- url: /
  script: python.main.app

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
  


libraries:
- name: webapp2
  version: "2.5.2"
  
- name: django
  version: latest

